// <auto-generated />
using System;
using ByteArrayTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ByteArrayTest.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20210228104608_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ByteArrayTest.Data.MyObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Objects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b763f4d6-8349-4ec0-b121-ea37eaac0f26"),
                            Name = "Testing 123"
                        },
                        new
                        {
                            Id = new Guid("665e5b61-c0a3-48bb-85a5-0359daa175a3"),
                            Name = "Testing 345"
                        },
                        new
                        {
                            Id = new Guid("9f161009-f1ba-46df-8923-396c36d0a9df"),
                            Name = "Testing 678"
                        },
                        new
                        {
                            Id = new Guid("fd3c7ed0-048e-44e3-a472-a7ef9cdd77b7"),
                            Name = "Testing 901"
                        },
                        new
                        {
                            Id = new Guid("57293055-8c01-4e14-858f-8c3846c45d48"),
                            Name = "Testing 234"
                        },
                        new
                        {
                            Id = new Guid("02ac0bc0-0509-458f-8523-90c15a5385bc"),
                            Name = "Testing 567"
                        },
                        new
                        {
                            Id = new Guid("7e51b4a4-0d49-4622-b386-f50f3790523a"),
                            Name = "Testing 890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
